language: node_js
sudo: required
node_js:
  - "11"
env:
  - CODECOV_TOKEN="cdbf54ad-128f-4c55-810a-3084cbce00af"
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
  - yarn install
  - cd ./backpacks/components && yarn install
script:
  - yarn run test
  - yarn run test:coverage
  - yarn build
