language: node_js
node_js:
  - "11"
install:
  - npm install
  - cd ./backpacks/components && npm install && cd ../../
script:
  - npm run lint
  - npm run test
  - npm run docs:build
  - cd ./backpacks/components && npm run build && cd../../
