language: node_js
node_js:
  - "8"
notifications:
  email: false
env:
  - CODECOV_TOKEN="cdbf54ad-128f-4c55-810a-3084cbce00af"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn --frozen-lockfile --non-interactive
jobs:
  include:
    - stage: test
      name: 'Lint and test'
      before_script:
        - yarn global add codecov
      script:
        - yarn run lint
        - yarn run test:coverage
      after_script:
        - codecov
    - stage: build
      name: 'Build test'
      script:
        - yarn run build
